site_name: Learning Parametric Koopman Documentation
# site_author: Yixiao Qian
# site_url: https://github.com/ReichtumQian
theme:
  name: material
  custom_dir: theme
  font: false
  logo: img/logo.bmp
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    # - navigation.expand
    # - navigation.tabs
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2
  # - section-index
  # - mkpdfs

extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

repo_name: 
repo_url: 

extra_css:
  - stylesheets/extra.css

nav:
  - User Guide:
    - Quick Start: "UserGuide/QuickStart.md"
  - Mathematics:
    - Parametric Koopman: "Mathematics/ParamKoopman.md"
    - EDMD Algorithm: "Mathematics/EDMD.md"
    - Duffing Equation: "Mathematics/Duffing.md"
    - Van der Pol Mathieu: "Mathematics/VanDerPolMathieu.md"
  - Class References:
    - Dictionary:
      - Class Dictionary: "ClassReferences/Dictionary.md"
      - Class TrainableDictionary: "ClassReferences/TrainableDictionary.md"
      - Class RBFDictionary: "ClassReferences/RBFDictionary.md"
    - Koopman Operator:
      - Class Koopman: "ClassReferences/Koopman.md"
      - Class ParamKoopman: "ClassReferences/ParamKoopman.md"
    - Solver:
      - Class EDMDSolver: "ClassReferences/EDMDSolver.md"
      - Class EDMDDLSolver: "ClassReferences/EDMDDLSolver.md"
      - Class ParamKoopmanDLSolver: "ClassReferences/ParamKoopmanDLSolver.md"
    - ODEs:
      - Class AbstractODE: "ClassReferences/AbstractODE.md"
      - Class DuffingOscillator: "ClassReferences/DuffingOscillator.md"
      - Class VanDerPolOscillator: "ClassReferences/VanDerPolOscillator.md"
    - Flow Map:
      - Class FlowMap: "ClassReferences/FlowMap.md"
      - Class ForwardEuler: "ClassReferences/ForwardEuler.md"
    - Data Management:
      - Class ODEDataSet: "ClassReferences/ODEDataSet.md"
      - Class ParamODEDataSet: "ClassReferences/ParamODEDataSet.md"
    - Neural Network:
      - Class FullConnBaseNet: "ClassReferences/FullConnBaseNet.md"
      - Class FullConnNet: "ClassReferences/FullConnNet.md"
      - Class FullConnResNet: "ClassReferences/FullConnResNet.md"
