site_name: Learning Parametric Koopman Documentation
theme:
  name: material
  custom_dir: theme
  font: false
  logo: img/logo.bmp
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - content.code.copy
    # - navigation.expand
    # - navigation.tabs
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 3
            show_source: false
            show_bases: true
            docstring_options: 
              returns_named_value: false
            
  # - section-index
  # - mkpdfs

extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

repo_name: 
repo_url: 

extra_css:
  - stylesheets/extra.css

nav:
  - Home: "index.md"
  - User Guide:
    - Set up the Environment: "UserGuide/Setup.md"
    - Quick Start: "UserGuide/QuickStart.md"
    - Input Guide: "UserGuide/InputGuide.md"
    - Customize Observables: "UserGuide/CustomizeObservable.md"
    - Customize ODE: "UserGuide/CustomizeODE.md"
    - Customize ODE Solver: "UserGuide/CustomizeODESolver.md"
    - Parallel Computing: "UserGuide/Parallel.md"
  - Class References:
    - Dictionary:
      - Class ObservableFunction: "ClassReferences/ObservableFunction.md"
      - Class Dictionary: "ClassReferences/Dictionary.md"
      - Class TrainableDictionary: "ClassReferences/TrainableDictionary.md"
      - Class RBFDictionary: "ClassReferences/RBFDictionary.md"
    - Koopman Operator:
      - Class Koopman: "ClassReferences/Koopman.md"
      - Class ParamKoopman: "ClassReferences/ParamKoopman.md"
      - Class KoopmanDynamics: "ClassReferences/KoopmanDynamics.md"
    - Koopman Solver:
      - Class EDMDSolver: "ClassReferences/EDMDSolver.md"
      - Class EDMDDLSolver: "ClassReferences/EDMDDLSolver.md"
      - Class ParamKoopmanDLSolver: "ClassReferences/ParamKoopmanDLSolver.md"
    - SolverWrapper:
      - Class SolverWrapper: "ClassReferences/SolverWrapper.md"
      - Class EDMDRBFSolverWrapper: "ClassReferences/EDMDRBFSolverWrapper.md"
      - Class EDMDDLSolverWrapper: "ClassReferences/EDMDDLSolverWrapper.md"
      - Class ParamKoopmanDLSolverWrapper: "ClassReferences/ParamKoopmanDLSolverWrapper.md"
    - ODEs:
      - Class AbstractODE: "ClassReferences/AbstractODE.md"
      - Class DiscreteDynamics: "ClassReferences/DiscreteDynamics.md"
    - ODE Solvers:
      - Class ODESolver: "ClassReferences/ODESolver.md"
    - Data Management:
      - Class KoopmanDataSet: "ClassReferences/KoopmanDataSet.md"
      - Class ParamKoopmanDataSet: "ClassReferences/ParamKoopmanDataSet.md"
    - Neural Network:
      - Class FullConnBaseNet: "ClassReferences/FullConnBaseNet.md"
      - Class FullConnNet: "ClassReferences/FullConnNet.md"
      - Class FullConnResNet: "ClassReferences/FullConnResNet.md"
    - SolverWrapper:
      - Class SolverWrapper: "ClassReferences/SolverWrapper.md"
      - Class EDMDRBFSolverWrapper: "ClassReferences/EDMDRBFSolverWrapper.md"
      - Class EDMDDLSolverWrapper: "ClassReferences/EDMDDLSolverWrapper.md"
      - Class ParamKoopmanDLSolverWrapper: "ClassReferences/ParamKoopmanDLSolverWrapper.md"
    - Optimal Control Solver:
      - Class KoopmanMPCSolver: "ClassReferences/KoopmanMPCSolver.md"
    - Factory:
      - Class Factory: "ClassReferences/Factory.md"
